### ISSUE TITLE
v8 backwards compatiblity

### ISSUE THREAD

**Issue by pnikonowicz** [pivotal-cf/brokerapi#161]
Can we get a backwards compatible commit in for the brokerapi v8 folder similar to what was done here for v7 please? 

https://github.com/pivotal-cf/brokerapi/commit/3d253be2ef4a4b719ecd8f368fed860bf2dc63f7

This is preventing us from consuming the latest broker-api. thanks for the help.

**Comment by FelisiaM** [comment]
Hi @pnikonowicz 

v8 is compatible with the currently maintained version of go dependency management (go mod). What I think you are requesting is compatibility with other dependency management tools that are no longer supported. 
Would you mind giving us some more details about what dependency manager you are using, and what is your timeline to move to go mods?

We could provide a folder for v8, however, that creates a more complicated setup for maintaining and contributing to this project and it is not our preferred long term solution. 

Thanks,
Felisia

**Comment by pnikonowicz** [comment]
we have never used a dependency management tool, and practically speaking, won't be able to. we just need the dependencies vendored in like before (see link in description). We currently cannot use the latest odb as a result. Providing a v8 folder (similar to the v7 folder that existed before) would help support us as a downstream consumer of these libraries. We aren't asking for anything complicated, we just want the v8 folder to exist just like the v7 folder used to.

**Comment by pnikonowicz** [comment]
Also, if all you're using is go mod, this might be helpful to you. https://golang.org/ref/mod#go-mod-vendor

**Comment by FelisiaM** [comment]
I understand the impact that this issue has on your team's project.

Just so I am clear is this issue happening as a result of updating  [ODB](https://github.com/pivotal-cf/cloudcache-service-adapter-release/commit/95c0194342a8a9836479c10d4f754610473a2e8d)  or [ODB SDK](https://github.com/pivotal-cf/cloudcache-service-adapter-release/commit/7d95c42fe94c0152dafa1a70ad52c249eb46350a)? Are you able to share with us the error?

The addition of a v8 folder is not preferred because it makes developing in this repo complex. The reason for this is that this project uses go mod and when a new versioned folder is added (as we did for v7) that becomes the place where go expects to find code that is imported from the main repo(unversioned files). This causes circular dependencies between the new code and the versioned one and it practically means that when code changes are made in the main code they need to continuously be copied to the versioned folder after every line change. 
Since this is a repo that has mainly open source contribution this setup made implementing any new feature and contributing to this repo much more difficult.

Sharing more about your consuming setup and error will help us figure out what is the best way to resolve the issue.

**Comment by pnikonowicz** [comment]
The error we see is with the odb-sdk. 
I understand what you mean. But you're talking about a process change that affects all downstream consumers without consulting with them first. We discovered the error after the v7 folder was deleted as we normally consume all of the latest odb-sdk releases. We can stop consuming the latest odb if that's your recommendation. I was hoping there would be a way to continue to use the process that we have been accustomed to these last few years.

**Comment by pnikonowicz** [comment]
it's for the odb-sdk. I appreciate the help. I suppose what we would need is instructions on how we can create the v8 folder ourselves so that we can fix the compilation issue.

**Comment by pnikonowicz** [comment]
is it possible for you to just run `go mod vendor` on the odb and the odb sdk please and then push the vendor directory?

**Comment by FelisiaM** [comment]
ODB already has all dependencies vendored in. The SDK is a library and it is not a recommended go practice to commit the vendor folder in this case.

I did notice you are using go submodule to manage your dependencies and brokerAPI is defined as a dependency there.
Can you try updating the [path](https://github.com/pivotal-cf/cloudcache-service-adapter-release/blob/23325033bae38f68c4be4dc53a6535e836ac3de7/.gitmodules#L78) to be `path = src/service-adapter/vendor/github.com/pivotal-cf/brokerapi/v8`. This should get the latest BrokerAPI main branch, put it in a v8 folder and should satisfy your requirement.

Let me know if this works.

**Comment by pnikonowicz** [comment]
That's just the tip of the iceberg for us unfortunately. Thanks for looking into this. 

In case anyone else is having issues with this, what we did was just fork the repo and run `go mod vendor`, then we push the changes back up again; essentially removing our submodule for the sdk and odb.
