### ISSUE TITLE
Feature request: Simple way to add prometheus exporter

### ISSUE THREAD

**Issue by MathieuCesbron** [pivotal-cf/brokerapi#192]
Hello,

From what I have seen, there is no easy way to add a metrics exporter (typically for Prometheus). We have to add it from scratch.

Adding a route /metrics by default or if we add a parameter would be interesting.

Example: operator-sdk is a framework to build kubernetes operator, it has a simple way to export metrics(https://docs.openshift.com/container-platform/4.9/operators/operator_sdk/osdk-monitoring-prometheus.html)

Have a good day,

**Comment by blgm** [comment]
Hi @MathieuCesbron. Thank you for your request.

I see the aim of the `brokerapi` package as translating between [OSBAPI over HTTP](https://github.com/openservicebrokerapi/servicebroker) and Go. I think this single purpose embodies the [single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle) as well as the [UNIX philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) to
>Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".

So I am initially hesitant to extend `brokerapi` to also provide a Prometheus metrics endpoint because:
- it complicates the purpose of `brokerapi`
- it could lead to requests to support other metrics platforms, and configuration around the metrics

But I realise that `brokerapi` needs to evolve to stay relevant, so I'm curious to understand a bit more about what you're aiming to achieve. What would the metrics data look like? Should it be configurable? Should it be persisted? Where there is more than one instance running, should the metrics be just for the instance queried, or should it be for all instances? Should `brokerapi` just delegate to another library that implements a Prometheus endpoint?

I'm wondering whether it might make sense to add a general purpose extension point that would make it easy to add a metrics endpoint, but without adding the complexity or opinions of metrics to `brokerapi`. For example, there could be a Go channel that receives some data every time that `brokerapi` handles a request.

I'd be interested to hear your thoughts.

I should also add that my team does not have the bandwidth to explore and implement this feature at the moment, but potentially we could merge a solution that was provided as a pull request.

Best wishes,

@blgm

**Comment by MathieuCesbron** [comment]
Hello @blgm and thanks for the answer.

I have not think much about what the metrics should look like at the moment. I am building something that uses a lot of operator and they natively expose metrics so I thought why not also let Prometheus scrape my broker data.

You made me realise that the best solution is probably to delegate it to a custom library. I will may be start it as a side project . 

Have a good day,
