### ISSUE TITLE
Async Deletion

### ISSUE THREAD

**Issue by cholick** [pivotal-cf/brokerapi#50]
Polling the last operation after deletion:
When deletion has concluded, the expected response code is 410 (https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#asynchronous-operations). The only way to get `LastOperation` to return that response code is using `brokerapi.NewFailureResponse`. This workaround results in error logging, which isn't appropriate given this is actually a success condition.

**Comment by mattmcneeney** [comment]
This sounds like a bug in ODB. @deniseyu you may want to prioritise this story as part of the OSBAPI compliance track.
cc @kieron-pivotal

**Comment by mattmcneeney** [comment]
Hey @cholick 
We've just taken a look at BrokerAPI to see how we could support this and, unfortunately, it doesn't look like there is a very elegant solution.

Returning a 200 to an async deprovision seems to be OK as per the spec, as a 200 response is defined as follows:
```
MUST be returned upon successful processing of this request. The expected response body is below.
```

The 410 response states `Appropriate only for asynchronous delete operations.`, not that it MUST be used.

We agree that we don't really want to log a valid 410 response as an error, but changing the interface to allow custom response codes to be returned via BrokerAPI would be a breaking change that we would like to avoid making.

Since Cloud Controller is happy receiving a 200 response in this case today, how would you feel about just returning a 200?

**Comment by cholick** [comment]
The backing service thinks differently about deleted vs created. The `operation` query param is optional, so we can't be assured of differentiating between the platform asking "are you deleted yet?" vs "are you created yet?" Returning 410 lets us say "yup, this is gone" and the platform can bubble up failure because it was expecting the resource have successfully created, not gone away.

I didn't dig into the code, but 410 is a legit response in DELETE `/v2/service_instances/:instance_id` too; guessing that suffers a similar issue.

**Comment by mattmcneeney** [comment]
According to the spec, if a broker returns the `operation` string when starting an async operation, that query param MUST be provided to the `last_operation` endpoint.

410 is definitely a legit response, and 200 also seems legit in this scenario!

**Comment by cholick** [comment]
I see, thanks. That does give is enough context to fail when needed. 200 it is.
