### ISSUE TITLE
Missing StatusOK 200

### ISSUE THREAD

**Issue by mrgunior** [pivotal-cf/brokerapi#69]
I am currently working on a service broker and I noticed that the brokerapi isn't returning StatusOK 200 and the respond() function isn't public either. In other words there isn't a way to properly get StatusOK 200 from the brokerapi.

I currently need this functionality as described by the [servicebrokerapi](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md) for [#provisioning](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#provisioning) and the [#binding](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#binding) when an instance/binding already exists and the requested parameters are identical to the existing instance/binding.

Any help or clarification on this matter would be appreciated.

**Comment by winnab** [comment]
Hey @mrgunior! 

Thanks for writing. We write brokerapi in conjunction with our [on-demand service broker](https://github.com/pivotal-cf/on-demand-service-broker), which interacts with CF. Interestingly and for some reason no one currently on the team knows, the on-demand broker doesn't follow spec, and our broker returns an [instance exists error](Use github.com/pivotal-cf/brokerapi/domain) error, which is handled in the broker api in the [error checking](Use github.com/pivotal-cf/brokerapi/domain).

In order to return the StatusOK 200, we thought of a couple of possibilities.

The provisionResponse could be extended to include a new property like `InstanceAlreadyExists`, and that could be checked after the broker returns. If it's true, return 200.

Or before the broker Provision gets called, there could be a call to the OSBAPI [GetInstance endpoint](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#fetching-a-service-instance). If the incoming ProvisionDetails match details from the result of GetInstance, return 200 and never ask the broker to provision. 

Were you thinking of other options?

Also our team would need time to make the change as we have other things active at the moment. Is this something you'd want to PR?

Thanks
Winna

**Comment by mrgunior** [comment]
Get instance won't work, since according to the specs provision should be the one to do these checks. Get instance also doesn't really help, since not all parameters are set by the user from upfront. There needs to be a thorough check between the local and the remote instance and a correct code response should be returned.

**Comment by winnab** [comment]
Thanks for getting to us @mrgunior. It sounds like you have an approach in mind. Do you have time/capacity to PR the work and tests for this?

**Comment by winnab** [comment]
Merged this functionality in https://github.com/pivotal-cf/brokerapi/pull/77
